CREATE TABLE sample
(
    SYNONYM_WORD VARCHAR(191) NOT NULL COMMENT 'シノニムワード',
    REPRESENTATIVE_WORD VARCHAR(191) NOT NULL COMMENT '代表ワード',
	  PRIMARY KEY (SYNONYM_WORD)
) COMMENT = 'シノニムワードと代表ワードの関係';